import { i18n } from "@/i18n-config";
import { toSlug } from "./utils";

 
export const data = {
   headerMenus: [
    {
      name: "Today's Deal",
      href: '/search?tag=todays-deal',
    },
    {
      name: 'New Arrivals',
      href: '/search?tag=new-arrival',
    },
    {
      name: 'Featured Products',
      href: '/search?tag=featured',
    },
    {
      name: 'Best Sellers',
      href: '/search?tag=best-seller',
    },
    {
      name: 'Browsing History',
      href: '/#browsing-history',
    },
    {
      name: 'Customer Service',
      href: '/page/customer-service',
    },
    {
      name: 'About Us',
      href: '/page/about-us',
    },
    {
      name: 'Help',
      href: '/page/help',
    },
  ],
   carousels: [
        {
          title: 'Glow Naturally with Herbal Skincare',
          buttonCaption: 'Shop Now',
          image: '/Images/banner1.png',
          url: '/search?category=Skincare',
        },
        {
          title: 'New Arrivals in Minimalist Jewellery',
          buttonCaption: 'Shop Now',
          image: '/Images/banner2.png',
          url: '/search?category=Jewellery',
        },
        {
          title: 'Elegant Sarees & Jewelry — Perfect Gifts',
          buttonCaption: 'See More',
          image: '/Images/banner3.png',
          url: '/search?category=saree',
        },
      ],

  featureSections : [
  {
    title: 'Categories to Explore',
    description: 'Browse by category',
    image: 'https://via.placeholder.com/400x250?text=Categories',
    slug: toSlug('Explore Categories'),
    items: [
      { name: 'Beauty', image: '/Images/beauty-category.jpg', href: '/search?category=beauty' },
      { name: 'Jewellery', image: '/Images/juwelery-category.jpeg', href: '/search?category=jewellery' },
      { name: 'Saree', image: '/Images/saree-category.jpeg', href: '/search?category=saree' },
      { name: 'Fashion', image: '/Images/fasion-category.jpeg', href: '/search?category=fashion' },
    ],
      link: {
      text: 'See More',
      href: '/search?type=categories',
    },
  },
  {
    title: 'Explore New Arrivals',
    description: 'Latest in beauty and fashion',
    image: 'https://via.placeholder.com/400x250?text=New+Arrivals',
    slug: toSlug('New Arrivals'),
    items: [
      { name: 'Lipstick', image: '/Images/lipstick-arivals.jpeg', href: '/search?tag=new&category=beauty' },
      { name: 'Earrings', image: '/Images/earrings-arivals.jpeg', href: '/search?tag=new&category=jewellery' },
      { name: 'Silk Saree', image: '/Images/silksaree-arivals.jpeg', href: '/search?tag=new&category=saree' },
      { name: 'Trendy Kurti', image: '/Images/trendykurti-arivals.jpeg', href: '/search?tag=new&category=fashion' },
    ],
        link: {
      text: 'View All',
      href: '/search?tag=new-arrival',
    },

  },
  {
    title: 'Discover Best Sellers',
    description: 'Top trending items',
    image: 'https://via.placeholder.com/400x250?text=Best+Sellers',
    slug: toSlug('Best Sellers'),
    items: [
      { name: 'Face Cream', image: '/Images/facecream-Bsellers.jpg', href: '/search?tag=best&category=beauty' },
      { name: 'Gold Necklace', image: '/Images/goldnekles-Bsellers.jpeg', href: '/search?tag=best&category=jewellery' },
      { name: 'Cotton Saree', image: '/Images/kottonsaree-Bsellers.jpeg', href: '/search?tag=best&category=saree' },
      { name: 'Casual Top', image: '/Images/casualtop-bsellers.jpg', href: '/search?tag=best&category=fashion' },
    ],
        link: {
      text: 'View All',
      href: '/search?tag=best-seller',
    },

  },
  {
    title: 'Featured Products',
    description: 'Editor\'s picks for you',
    image: 'https://via.placeholder.com/400x250?text=Featured+Products',
    slug: toSlug('Featured Products'),
    items: [
      { name: 'Compact Powder', image: '/Images/compactpowder-features.jpg', href: '/search?tag=featured&category=beauty' },
      { name: 'Bracelet', image: '/Images/breslate-features.jpg', href: '/search?tag=featured&category=jewellery' },
      { name: 'Designer Saree', image: '/Images/designersaree-features.jpg', href: '/search?tag=featured&category=saree' },
      { name: 'Party Dress', image: '/Images/partydress-features.jpg', href: '/search?tag=featured&category=fashion' },
    ],
     link: {
      text: 'Shop Now',
      href: '/search?tag=featured',
    },
  },
],

  todaysDeals : [
  {
    _id: '1',
    slug: 'diamond-jewelry-set',
    name: 'Luxury Diamond Jewelry Set',
    brand: 'Elegancia',
    description: 'Elegant diamond necklace and earrings set with fine craftsmanship, perfect for weddings and celebrations.',
    images: ['/Images/todays-deal1.jpg', '/Images/todays-deal11.jpg'],
    price: 9600,
    listPrice: 12000,
    avgRating: 4.8,
    numReviews: 123,
    category: 'jewelry',
    tags: ['todays-deal'],
    sizes: ['Free'],
    colors: ['Silver'],
    countInStock: 10,
  },
  {
    _id: '2',
    slug: 'banarasi-silk-saree',
    name: 'Branded Banarasi Silk Saree',
    brand: 'Sundori Sarees',
    description: 'Premium Banarasi silk saree with golden zari work — a timeless ethnic fashion piece.',
    images: ['/Images/todays-deal2.jpeg', '/Images/today-deal22.jpeg'],
    price: 7225,
    listPrice: 8500,
    avgRating: 4.6,
    numReviews: 98,
    category: 'saree',
    tags: ['todays-deal'],
    sizes: ['Free'],
    colors: ['Red'],
    countInStock: 15,
  },
  {
    _id: '3',
    slug: 'organic-skincare-pack',
    name: 'Organic Skincare Essentials',
    brand: 'Glow Naturals',
    description: 'A complete skincare combo including face wash, toner, and night cream — made with organic ingredients.',
    images: ['/Images/todays-deal3.jpg', '/Images/today-deal32.jpeg'],
    price: 1450,
    listPrice: 1800,
    avgRating: 4.4,
    numReviews: 75,
    category: 'beauty',
    tags: ['todays-deal'],
    sizes: ['Standard'],
    colors: ['N/A'],
    countInStock: 25,
  },
  {
    _id: '4',
    slug: 'gold-plated-bracelet',
    name: 'Gold Plated Bracelet',
    brand: 'Shine Luxe',
    description: 'Trendy gold plated bracelet for women with modern design, perfect for everyday wear or gifting.',
    images: ['/Images/todays-deal4.jpg', '/Images/todays-deal-42.jpg'],
    price: 899,
    listPrice: 1200,
    avgRating: 4.3,
    numReviews: 64,
    category: 'jewelry',
    tags: ['todays-deal'],
    sizes: ['Free'],
    colors: ['Gold'],
    countInStock: 20,
  },
  {
    _id: '5',
    slug: 'western-casual-dress',
    name: 'Western Casual Dress',
    brand: 'StyleUp',
    description: 'Chic western wear dress with floral prints — comfortable and stylish for casual outings.',
    images: ['/Images/todays-deal5.jpg', '/Images/todays-deal-52.jpg'],
    price: 1890,
    listPrice: 2400,
    avgRating: 4.5,
    numReviews: 81,
    category: 'fashion',
    tags: ['todays-deal'],
    sizes: ['S', 'M', 'L'],
    colors: ['Blue'],
    countInStock: 18,
  },
],


  settings: [
    {
      common: {
        freeShippingMinPrice: 35,
        isMaintenanceMode: false,
        defaultTheme: 'Light',
        defaultColor: 'Gold',
        pageSize: 9,
      },
      site: {
        name: 'ShopNext',
        description:
          'ShopNext is a sample Ecommerce website built with Next.js, Tailwind CSS, and MongoDB.',
        keywords: 'Next Ecommerce, Next.js, Tailwind CSS, MongoDB',
        url: 'https://next-mongo-ecommerce-final.vercel.app',
        logo: '/icons/logo.svg',
        slogan: 'Spend less, enjoy more.',
        author: 'Next Ecommerce',
        copyright: '2000-2024, Next-Ecommerce.com, Inc. or its affiliates',
        email: 'admin@example.com',
        address: '123, Main Street, Anytown, CA, Zip 12345',
        phone: '+1 (123) 456-7890',
      },
      carousels: [
        {
          title: 'Most Popular Shoes For Sale',
          buttonCaption: 'Shop Now',
          image: '/images/banner3.jpg',
          url: '/search?category=Shoes',
        },
        {
          title: 'Best Sellers in T-Shirts',
          buttonCaption: 'Shop Now',
          image: '/images/banner1.jpg',
          url: '/search?category=T-Shirts',
        },
        {
          title: 'Best Deals on Wrist Watches',
          buttonCaption: 'See More',
          image: '/images/banner2.jpg',
          url: '/search?category=Wrist Watches',
        },
      ],
      availableLanguages: i18n.locales.map((locale) => ({
        code: locale.code,
        name: locale.name,
      })),
      defaultLanguage: 'en-US',
      availableCurrencies: [
        {
          name: 'United States Dollar',
          code: 'USD',
          symbol: '$',
          convertRate: 1,
        },
        { name: 'Euro', code: 'EUR', symbol: '€', convertRate: 0.96 },
        { name: 'UAE Dirham', code: 'AED', symbol: 'AED', convertRate: 3.67 },
      ],
      defaultCurrency: 'USD',
      availablePaymentMethods: [
        { name: 'PayPal', commission: 0 },
        { name: 'Stripe', commission: 0 },
        { name: 'Cash On Delivery', commission: 0 },
      ],
      defaultPaymentMethod: 'PayPal',
      availableDeliveryDates: [
        {
          name: 'Tomorrow',
          daysToDeliver: 1,
          shippingPrice: 12.9,
          freeShippingMinPrice: 0,
        },
        {
          name: 'Next 3 Days',
          daysToDeliver: 3,
          shippingPrice: 6.9,
          freeShippingMinPrice: 0,
        },
        {
          name: 'Next 5 Days',
          daysToDeliver: 5,
          shippingPrice: 4.9,
          freeShippingMinPrice: 35,
        },
      ],
      defaultDeliveryDate: 'Next 5 Days',
    },
  ],

 bestSellingProducts : [
  {
    _id: '1',
    slug: 'diamond-jewelry-set',
    name: 'Luxury Diamond Jewelry Set',
    brand: 'Elegancia',
    description: 'Elegant diamond necklace and earrings set with fine craftsmanship, perfect for weddings and celebrations.',
    images: ['/Images/bestleling-diamond1.jpg', '/Images/bestseling-diamond2.jpg'],
    price: 9600,
    listPrice: 12000,
    avgRating: 4.8,
    numReviews: 123,
    category: 'jewelry',
    tags: ['todays-deal', 'wedding'],
    sizes: ['Free'],
    colors: ['Silver'],
    countInStock: 10,
  },
 {
    _id: '2',
    slug: 'gold-plated-face-mask',
    name: 'Traditional Gold-Plated Face Mask',
    brand: 'Nokshi Beauty',
    description: 'Luxurious gold-infused face mask set, perfect for festive skin care routines.',
    images: ['/Images/bestseling-goldfacem-1.png', '/Images/bestseling-goldfacem2.jpeg'],
    price: 2200,
    listPrice: 2800,
    avgRating: 4.4,
    numReviews: 75,
    category: 'beauty',
    tags: ['gold', 'face-mask'],
    sizes: ['Free'],
    colors: ['Gold'],
    countInStock: 20,
  },
  {
    _id: '3',
    slug: 'cosmetic-necklace-set',
    name: 'Cosmetic Style Necklace Set',
    brand: 'FashionZone',
    description: 'Trendy costume necklace set perfect for parties and casual events.',
    images: ['/Images/bestseling-cousmeticnekles1.jpg', '/Images/bestseling-cousmeticnekles2.jpg'],
    price: 1299,
    listPrice: 1600,
    avgRating: 4.3,
    numReviews: 78,
    category: 'jewelry',
    tags: ['cosmetic', 'party'],
    sizes: ['Free'],
    colors: ['Black', 'Golden'],
    countInStock: 15,
  },
  {
    _id: '4',
    slug: 'diamond-glow-serum',
    name: 'Diamond Glow Face Serum',
    brand: 'Shonar Bangla Beauty',
    description: 'A brightening serum with diamond-like shine for radiant skin.',
    images: ['/Images/bestseling-serum1.jpeg', '/Images/bestseling-serum2.jpeg'],
    price: 4500,
    listPrice: 5200,
    avgRating: 4.7,
    numReviews: 65,
    category: 'beauty',
    tags: ['serum', 'diamond', 'glow'],
    sizes: ['Free'],
    colors: ['Silver'],
    countInStock: 9,
  },
  
  
  {
    _id: '5',
    slug: 'colorful-bangles-set',
    name: 'Colorful Bangles Set',
    brand: 'Shaadimela',
    description: 'All-in-one wedding bridal jewelry set for traditional Bengali weddings.',
    images: ['/Images/bestselinkg-churi1.jpg', '/Images/bestseling-churi.jpg'],
    price: 8999,
    listPrice: 11000,
    avgRating: 4.9,
    numReviews: 210,
    category: 'jewelry',
    tags: ['wedding', 'bridal'],
    sizes: ['Free'],
    colors: ['Gold', 'Red'],
    countInStock: 5,
  },
 {
    _id: '6',
    slug: 'pearl-skin-care-set',
    name: 'Classic Pearl Skin Care Set',
    brand: 'PearlLuxe',
    description: 'Elegant skincare combo with pearl essence, perfect for glowing skin before formal events.',
    images: ['/Images/bestseling-skincare1.jpeg', '/Images/bestseling-skincare2.jpeg'],
    price: 3500,
    listPrice: 4200,
    avgRating: 4.6,
    numReviews: 88,
    category: 'beauty',
    tags: ['pearl', 'skincare'],
    sizes: ['Free'],
    colors: ['White'],
    countInStock: 12,
  },
   {
    _id: '7',
    slug: 'benaroshi-set',
    name: 'Traditional Benaroshi Jewelry Set',
    brand: 'Rajkonna',
    description: 'Perfect matching gold-plated jewelry for Benaroshi saree – includes tikli, earrings, necklace and bangles.',
    images: ['/Images/bestseling-benarosi1.jpeg', '/Images/bestseling-benarosi2.jpg'],
    price: 5500,
    listPrice: 7500,
    avgRating: 4.7,
    numReviews: 96,
    category: 'jewelry',
    tags: ['benaroshi', 'wedding'],
    sizes: ['Free'],
    colors: ['Gold'],
    countInStock: 7,
  },
  {
    _id: '8',
    slug: 'payel-silver-design',
    name: 'Silver Designer Payel (Anklet)',
    brand: 'PayelWorld',
    description: 'Modern yet traditional silver payel for festive and daily wear.',
    images: ['/Images/besttseling-payel1.jpg', '/Images/bestseling-payel2.jpg'],
    price: 950,
    listPrice: 1250,
    avgRating: 4.5,
    numReviews: 50,
    category: 'jewelry',
    tags: ['anklet', 'silver'],
    sizes: ['Free'],
    colors: ['Silver'],
    countInStock: 25,
  },
  {
    _id: '9',
    slug: 'golden-glow-pack',
    name: 'Golden Glow Skin Pack',
    brand: 'RoyalGlow',
    description: 'Premium golden facial kit for instant brightness with a festive finish.',
    images: ['/Images/bestseling-glowpack1.jpeg', '/Images/bestseling-glowpack2.jpg'],
    price: 7000,
    listPrice: 8500,
    avgRating: 4.8,
    numReviews: 130,
    category: 'beauty',
    tags: ['golden', 'facial'],
    sizes: ['Free'],
    colors: ['Gold'],
    countInStock: 8,
  },
  {
    _id: '10',
    slug: 'silver-foot-cream',
    name: 'Elegant Silver Foot Cream',
    brand: 'SilverLine Care',
    description: 'Soothing silver-based foot cream ideal for daily refreshing care.',
    images: ['/Images/bestseling-footcream1.jpg', '/Images/bestseling-footcream2.jpeg'],
    price: 750,
    listPrice: 950,
    avgRating: 4.3,
    numReviews: 47,
    category: 'beauty',
    tags: ['foot', 'silver', 'cream'],
    sizes: ['Free'],
    colors: ['Silver'],
    countInStock: 30,
  },
  {
    _id: '11',
    slug: 'wedding-beauty-ring-kit',
    name: 'Wedding Beauty Ring Kit',
    brand: 'Romance Beauty',
    description: 'Elegant skincare and nail care kit designed for couples’ wedding glow.',
    images: ['/Images/bestseling-ring1.jpeg', '/Images/bestseling-ring2.jpeg'],
    price: 5500,
    listPrice: 6500,
    avgRating: 4.9,
    numReviews: 90,
    category: 'beauty',
    tags: ['wedding', 'couple', 'kit'],
    sizes: ['6', '7', '8'],
    colors: ['Gold', 'Silver'],
    countInStock: 15,
  },
],

 relatedProducts : [
  {
    _id: '101',
    slug: 'diamond-necklace-set',
    name: 'Luxury Diamond Necklace Set',
    brand: 'Elegancia',
    description: 'Exquisite diamond necklace and matching earrings, perfect for weddings and parties.',
    images: ['/images/jewellery/diamond-necklace1.jpg', '/images/jewellery/diamond-necklace2.jpg'],
    price: 9500,
    listPrice: 12000,
    avgRating: 4.9,
    numReviews: 85,
    category: 'jewellery',
    tags: ['related', 'featured'],
    sizes: ['Free'],
    colors: ['Silver', 'White Gold'],
    countInStock: 12,
  },
  {
    _id: '102',
    slug: 'pearl-bracelet-beauty',
    name: 'Elegant Pearl Bracelet',
    brand: 'Shundori',
    description: 'Beautiful handcrafted pearl bracelet to enhance your look.',
    images: ['/images/beauty/pearl-bracelet1.jpg', '/images/beauty/pearl-bracelet2.jpg'],
    price: 1200,
    listPrice: 1500,
    avgRating: 4.7,
    numReviews: 40,
    category: 'beauty',
    tags: ['related'],
    sizes: ['Free'],
    colors: ['White'],
    countInStock: 25,
  },
  {
    _id: '103',
    slug: 'gold-plated-earrings',
    name: 'Gold Plated Earrings',
    brand: 'Nokshi',
    description: 'Traditional gold-plated earrings perfect for festivals and ceremonies.',
    images: ['/images/jewellery/gold-earrings1.jpg', '/images/jewellery/gold-earrings2.jpg'],
    price: 1500,
    listPrice: 1900,
    avgRating: 4.5,
    numReviews: 55,
    category: 'jewellery',
    tags: ['related'],
    sizes: ['Free'],
    colors: ['Gold'],
    countInStock: 30,
  },
  {
    _id: '104',
    slug: 'herbal-face-pack',
    name: 'Herbal Face Pack',
    brand: 'HerbGlow',
    description: 'Natural herbal face pack for glowing and fresh skin.',
    images: ['/images/beauty/herbal-face-pack1.jpg', '/images/beauty/herbal-face-pack2.jpg'],
    price: 800,
    listPrice: 1100,
    avgRating: 4.6,
    numReviews: 70,
    category: 'beauty',
    tags: ['related'],
    sizes: ['Free'],
    colors: ['Green'],
    countInStock: 40,
  },
  {
    _id: '105',
    slug: 'kundan-necklace-set',
    name: 'Kundan Necklace Set',
    brand: 'Bengal Looms',
    description: 'Premium Kundan necklace with matching earrings, handcrafted with detail.',
    images: ['/images/jewellery/kundan-necklace1.jpg', '/images/jewellery/kundan-necklace2.jpg'],
    price: 8500,
    listPrice: 10000,
    avgRating: 4.8,
    numReviews: 65,
    category: 'jewellery',
    tags: ['related'],
    sizes: ['Free'],
    colors: ['Gold', 'Silver'],
    countInStock: 15,
  },
  {
    _id: '106',
    slug: 'aloe-vera-skin-gel',
    name: 'Aloe Vera Skin Gel',
    brand: 'GlowCare',
    description: 'Soothing aloe vera gel for moisturized and healthy skin.',
    images: ['/images/beauty/aloe-vera1.jpg', '/images/beauty/aloe-vera2.jpg'],
    price: 500,
    listPrice: 700,
    avgRating: 4.4,
    numReviews: 60,
    category: 'beauty',
    tags: ['related'],
    sizes: ['Free'],
    colors: ['Green'],
    countInStock: 50,
  },
  {
    _id: '107',
    slug: 'pearl-earrings-set',
    name: 'Pearl Earrings Set',
    brand: 'Shonar Bangla',
    description: 'Elegant pearl earrings set with diamond-like shine.',
    images: ['/images/jewellery/pearl-earrings1.jpg', '/images/jewellery/pearl-earrings2.jpg'],
    price: 2200,
    listPrice: 2700,
    avgRating: 4.7,
    numReviews: 50,
    category: 'jewellery',
    tags: ['related'],
    sizes: ['Free'],
    colors: ['White'],
    countInStock: 20,
  },
  {
    _id: '108',
    slug: 'gold-bangles-set',
    name: 'Gold Bangles Set',
    brand: 'Nokshi',
    description: 'Traditional gold bangles set for festive occasions.',
    images: ['/images/jewellery/gold-bangles1.jpg', '/images/jewellery/gold-bangles2.jpg'],
    price: 3000,
    listPrice: 3500,
    avgRating: 4.5,
    numReviews: 40,
    category: 'jewellery',
    tags: ['related'],
    sizes: ['Free'],
    colors: ['Gold'],
    countInStock: 18,
  },
  {
    _id: '109',
    slug: 'face-serum-glow',
    name: 'Face Serum Glow',
    brand: 'HerbGlow',
    description: 'Brightening face serum for youthful skin glow.',
    images: ['/images/beauty/face-serum1.jpg', '/images/beauty/face-serum2.jpg'],
    price: 900,
    listPrice: 1200,
    avgRating: 4.6,
    numReviews: 55,
    category: 'beauty',
    tags: ['related'],
    sizes: ['Free'],
    colors: ['Transparent'],
    countInStock: 35,
  },
  {
    _id: '110',
    slug: 'benarosi-payel',
    name: 'Benarosi Payel',
    brand: 'Traditional',
    description: 'Authentic Benarosi payel for cultural and festive wear.',
    images: ['/images/jewellery/benarosi-payel1.jpg', '/images/jewellery/benarosi-payel2.jpg'],
    price: 1800,
    listPrice: 2200,
    avgRating: 4.7,
    numReviews: 30,
    category: 'jewellery',
    tags: ['related'],
    sizes: ['Free'],
    colors: ['Silver'],
    countInStock: 10,
  }
]

  
}